<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'labeltest' => '/test/LabelTest.php',
                'mangofp\\adminroutes' => '/src/Adapters/AdminRoutes.php',
                'mangofp\\cf7connector' => '/src/Adapters/CF7Connector.php',
                'mangofp\\entities\\baseentity' => '/src/Entities/BaseEntity.php',
                'mangofp\\entities\\historyitem' => '/src/Entities/HistoryItem.php',
                'mangofp\\entities\\label' => '/src/Entities/Label.php',
                'mangofp\\entities\\message' => '/src/Entities/Message.php',
                'mangofp\\localization' => '/src/Adapters/Localization.php',
                'mangofp\\messagesdb' => '/src/Adapters/MessagesDB.php',
                'mangofp\\usecases\\ioutput' => '/src/UseCases/iOutput.php',
                'mangofp\\usecases\\istorage' => '/src/UseCases/iStorage.php',
                'mangofp\\usecases\\labelsusecase' => '/src/UseCases/LabelsUseCase.php',
                'mangofp\\usecases\\messageusecase' => '/src/UseCases/MessageUseCase.php',
                'messagesusecasetest' => '/test/MessagesUseCaseTest.php',
                'messagetest' => '/test/MessageTest.php',
                'mockoutput' => '/test/Mockups/MockOutput.php',
                'mockstorage' => '/test/Mockups/MockStorage.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
