<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'adminroutes' => '/src/controllers/AdminRoutes.php',
                'message' => '/src/entities/Message.php',
                'messagesdata' => '/src/data/MessagesData.php',
                'messagetest' => '/test/MessageTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
